#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rapdos-s <rapdos-s@student.42sp.org.br>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/16 06:58:34 by rapdos-s          #+#    #+#              #
#    Updated: 2024/02/16 07:01:45 by rapdos-s         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME	 = libft.a

################################################################################

all: ${NAME} bonus
	@echo "all"

$(NAME):
	@echo ${NAME}

bonus:
	@echo "bonus"

clean:
	@echo "clean"

fclean: clean
	@echo "fclean"

re: fclean all
	@echo "re"

.PHONY: all bonus clean fclean re
################################################################################

duck:
	@echo "Furious quacking noises!"

.PHONY: duck